In [29]:
# Import dependencies
import pandas as pd
from pathlib import Path
import hvplot.pandas
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [3]:
# Read in the CSV file as a Pandas DataFrame
Airbnb_df = pd.read_csv(Path(r"C:\Users\Sezy\OneDrive\last_project_for_it\Airbnb_Score_Model\Resources\Airbnb_Data.csv"))

# Review the DataFrame
Airbnb_df.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [4]:
Airbnb_df.shape[0]

74111

In [5]:
# Check to look for missing data. 
columns_to_check = [
    'log_price', 
    'property_type', 
    'accommodates', 
    'bathrooms', 
    'cancellation_policy', 
    'cleaning_fee', 
    'review_scores_rating', 
    'zipcode'
]
# Drop all missing data
Airbnb_df = Airbnb_df.dropna(subset=columns_to_check)
Airbnb_df.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0
5,12422935,4.442651,Apartment,Private room,"{TV,""Wireless Internet"",Heating,""Smoke detecto...",2,1.0,Real Bed,strict,True,...,37.753164,-122.429526,Comfort Suite San Francisco,Noe Valley,3,100.0,https://a0.muscache.com/im/pictures/82509143-4...,94131,1.0,1.0

In [14]:
Airbnb_df.shape[0]

56556

Dropping Columns that are not helpful

In [6]:
Airbnb_df = Airbnb_df.drop(columns=['id','room_type','latitude', 'longitude','name','neighbourhood','thumbnail_url'])
Airbnb_df.head()

,log_price,property_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,description,...,host_identity_verified,host_response_rate,host_since,instant_bookable,last_review,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,5.010635,Apartment,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,NYC,"Beautiful, sunlit brownstone 1-bedroom in the ...",...,t,NaN,2012-03-26,f,2016-07-18,2,100.0,11201,1.0,1.0
1,5.129899,Apartment,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,NYC,Enjoy travelling during your stay in Manhattan...,...,f,100%,2017-06-19,t,2017-09-23,6,93.0,10019,3.0,3.0
2,4.976734,Apartment,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,NYC,The Oasis comes complete with a full backyard ...,...,t,100%,2016-10-25,t,2017-09-14,10,92.0,10027,1.0,3.0
4,4.744932,Apartment,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,DC,"Cool, cozy, and comfortable studio located in ...",...,t,100%,2015-03-01,t,2017-01-22,4,40.0,20009,0.0,1.0
5,4.442651,Apartment,"{TV,""Wireless Internet"",Heating,""Smoke detecto...",2,1.0,Real Bed,strict,True,SF,Beautiful private room overlooking scenic view...,...,t,100%,2017-06-07,t,2017-09-05,3,100.0,94131,1.0,1.0

In [7]:
Airbnb_df = Airbnb_df.drop(columns=['host_response_rate', 'host_since', 'description', 'bed_type', 'last_review'])
Airbnb_df.head()

,log_price,property_type,amenities,accommodates,bathrooms,cancellation_policy,cleaning_fee,city,first_review,host_has_profile_pic,host_identity_verified,instant_bookable,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,5.010635,Apartment,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,strict,True,NYC,2016-06-18,t,t,f,2,100.0,11201,1.0,1.0
1,5.129899,Apartment,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,strict,True,NYC,2017-08-05,t,f,t,6,93.0,10019,3.0,3.0
2,4.976734,Apartment,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,moderate,True,NYC,2017-04-30,t,t,t,10,92.0,10027,1.0,3.0
4,4.744932,Apartment,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,moderate,True,DC,2015-05-12,t,t,t,4,40.0,20009,0.0,1.0
5,4.442651,Apartment,"{TV,""Wireless Internet"",Heating,""Smoke detecto...",2,1.0,strict,True,SF,2017-08-27,t,t,t,3,100.0,94131,1.0,1.0

In [8]:
Airbnb_df = Airbnb_df.drop(columns=['amenities', 'first_review', 'zipcode'])

Checking Unique words to determine how to onehot code columns

In [9]:
unique_cancellation_policies = Airbnb_df['cancellation_policy'].unique()
unique_property_types = Airbnb_df['property_type'].unique()
unique_city_types = Airbnb_df['city'].unique()

In [10]:
print(unique_city_types)

['NYC' 'DC' 'SF' 'LA' 'Chicago' 'Boston']

Target and Features

In [11]:
X = Airbnb_df.drop(columns=['review_scores_rating'])
y = Airbnb_df['review_scores_rating']

In [12]:
y

0        100.0
1         93.0
2         92.0
4         40.0
5        100.0
         ...
74104    100.0
74105     91.0
74107     93.0
74108     94.0
74110     96.0
Name: review_scores_rating, Length: 56556, dtype: float64

In [13]:
X

,log_price,property_type,accommodates,bathrooms,cancellation_policy,cleaning_fee,city,host_has_profile_pic,host_identity_verified,instant_bookable,number_of_reviews,bedrooms,beds
0,5.010635,Apartment,3,1.0,strict,True,NYC,t,t,f,2,1.0,1.0
1,5.129899,Apartment,7,1.0,strict,True,NYC,t,f,t,6,3.0,3.0
2,4.976734,Apartment,5,1.0,moderate,True,NYC,t,t,t,10,1.0,3.0
4,4.744932,Apartment,2,1.0,moderate,True,DC,t,t,t,4,0.0,1.0
5,4.442651,Apartment,2,1.0,strict,True,SF,t,t,t,3,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74104,4.356709,Apartment,2,1.0,strict,True,Chicago,t,t,f,6,1.0,1.0
74105,4.248495,House,2,1.0,moderate,True,LA,t,t,f,36,1.0,1.0
74107,5.043425,Apartment,4,2.0,moderate,True,LA,t,f,f,16,2.0,4.0
74108,5.220356,Apartment,5,1.0,moderate,True,NYC,t,t,t,43,2.0,2.0
74110,4.852030,Boat,4,1.0,moderate,False,LA,t,t,f,205,1.0,2.0

In [14]:
print(Airbnb_df.dtypes)

log_price                 float64
property_type              object
accommodates                int64
bathrooms                 float64
cancellation_policy        object
cleaning_fee                 bool
city                       object
host_has_profile_pic       object
host_identity_verified     object
instant_bookable           object
number_of_reviews           int64
review_scores_rating      float64
bedrooms                  float64
beds                      float64
dtype: object

In [21]:
# Generate our categorical variable lists
categorical_features = Airbnb_df.dtypes[Airbnb_df.dtypes == "object"].index.tolist()

In [23]:
# Check the number of unique values in each column
Airbnb_df[categorical_features].nunique()

property_type             32
cancellation_policy        5
city                       6
host_has_profile_pic       2
host_identity_verified     2
instant_bookable           2
dtype: int64

In [24]:
numeric_features = X.select_dtypes(include='number')

In [25]:
numeric_features.nunique()

log_price            664
accommodates          16
bathrooms             17
number_of_reviews    370
bedrooms              11
beds                  18
dtype: int64

In [26]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [27]:
# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(Airbnb_df[categorical_features]))

c:\Users\Sezy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [31]:
# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names_out(categorical_features)
encode_df.head()

,property_type_Apartment,property_type_Bed & Breakfast,property_type_Boat,property_type_Boutique hotel,property_type_Bungalow,property_type_Cabin,property_type_Camper/RV,property_type_Castle,property_type_Cave,property_type_Chalet,...,city_NYC,city_SF,host_has_profile_pic_f,host_has_profile_pic_t,host_has_profile_pic_nan,host_identity_verified_f,host_identity_verified_t,host_identity_verified_nan,instant_bookable_f,instant_bookable_t
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [35]:
# Merge one-hot encoded features and drop the originals
Airbnb_df = Airbnb_df.merge(encode_df,left_index=True, right_index=True)
Airbnb_df = Airbnb_df.drop(columns=categorical_features)
Airbnb_df.head()

,log_price,accommodates,bathrooms,cleaning_fee,number_of_reviews,review_scores_rating,bedrooms,beds,property_type_Apartment_x,property_type_Bed & Breakfast_x,...,city_NYC,city_SF,host_has_profile_pic_f,host_has_profile_pic_t,host_has_profile_pic_nan,host_identity_verified_f,host_identity_verified_t,host_identity_verified_nan,instant_bookable_f,instant_bookable_t
0,5.010635,3,1.0,True,2,100.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1,5.129899,7,1.0,True,6,93.0,3.0,3.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,4.976734,5,1.0,True,10,92.0,1.0,3.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,4.744932,2,1.0,True,4,40.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
5,4.442651,2,1.0,True,3,100.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [37]:
Airbnb_df = Airbnb_df.drop(columns='cleaning_fee')

In [39]:
encoded_Airbnb_df = Airbnb_df.copy()
encoded_Airbnb_df

,log_price,accommodates,bathrooms,number_of_reviews,review_scores_rating,bedrooms,beds,property_type_Apartment_x,property_type_Bed & Breakfast_x,property_type_Boat_x,...,city_NYC,city_SF,host_has_profile_pic_f,host_has_profile_pic_t,host_has_profile_pic_nan,host_identity_verified_f,host_identity_verified_t,host_identity_verified_nan,instant_bookable_f,instant_bookable_t
0,5.010635,3,1.0,2,100.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1,5.129899,7,1.0,6,93.0,3.0,3.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,4.976734,5,1.0,10,92.0,1.0,3.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,4.744932,2,1.0,4,40.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
5,4.442651,2,1.0,3,100.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56550,4.382027,1,1.0,3,100.0,1.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
56551,4.969813,2,1.0,18,98.0,1.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
56552,5.356586,10,1.0,23,91.0,2.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
56553,3.688879,1,1.0,1,100.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
56554,4.304065,2,1.0,46,93.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [46]:
print(Airbnb_df.columns.tolist())

['log_price', 'accommodates', 'bathrooms', 'number_of_reviews', 'review_scores_rating', 'bedrooms', 'beds', 'property_type_Apartment_x', 'property_type_Bed & Breakfast_x', 'property_type_Boat_x', 'property_type_Boutique hotel_x', 'property_type_Bungalow_x', 'property_type_Cabin_x', 'property_type_Camper/RV_x', 'property_type_Castle_x', 'property_type_Cave_x', 'property_type_Chalet_x', 'property_type_Condominium_x', 'property_type_Dorm_x', 'property_type_Earth House_x', 'property_type_Guest suite_x', 'property_type_Guesthouse_x', 'property_type_Hostel_x', 'property_type_House_x', 'property_type_Hut_x', 'property_type_In-law_x', 'property_type_Island_x', 'property_type_Loft_x', 'property_type_Other_x', 'property_type_Serviced apartment_x', 'property_type_Tent_x', 'property_type_Timeshare_x', 'property_type_Tipi_x', 'property_type_Townhouse_x', 'property_type_Train_x', 'property_type_Treehouse_x', 'property_type_Vacation home_x', 'property_type_Villa_x', 'property_type_Yurt_x', 'cancellation_policy_flexible_x', 'cancellation_policy_moderate_x', 'cancellation_policy_strict_x', 'cancellation_policy_super_strict_30_x', 'cancellation_policy_super_strict_60_x', 'city_Boston_x', 'city_Chicago_x', 'city_DC_x', 'city_LA_x', 'city_NYC_x', 'city_SF_x', 'host_has_profile_pic_f_x', 'host_has_profile_pic_t_x', 'host_has_profile_pic_nan_x', 'host_identity_verified_f_x', 'host_identity_verified_t_x', 'host_identity_verified_nan_x', 'instant_bookable_f_x', 'instant_bookable_t_x', 'property_type_Apartment_y', 'property_type_Bed & Breakfast_y', 'property_type_Boat_y', 'property_type_Boutique hotel_y', 'property_type_Bungalow_y', 'property_type_Cabin_y', 'property_type_Camper/RV_y', 'property_type_Castle_y', 'property_type_Cave_y', 'property_type_Chalet_y', 'property_type_Condominium_y', 'property_type_Dorm_y', 'property_type_Earth House_y', 'property_type_Guest suite_y', 'property_type_Guesthouse_y', 'property_type_Hostel_y', 'property_type_House_y', 'property_type_Hut_y', 'property_type_In-law_y', 'property_type_Island_y', 'property_type_Loft_y', 'property_type_Other_y', 'property_type_Serviced apartment_y', 'property_type_Tent_y', 'property_type_Timeshare_y', 'property_type_Tipi_y', 'property_type_Townhouse_y', 'property_type_Train_y', 'property_type_Treehouse_y', 'property_type_Vacation home_y', 'property_type_Villa_y', 'property_type_Yurt_y', 'cancellation_policy_flexible_y', 'cancellation_policy_moderate_y', 'cancellation_policy_strict_y', 'cancellation_policy_super_strict_30_y', 'cancellation_policy_super_strict_60_y', 'city_Boston_y', 'city_Chicago_y', 'city_DC_y', 'city_LA_y', 'city_NYC_y', 'city_SF_y', 'host_has_profile_pic_f_y', 'host_has_profile_pic_t_y', 'host_has_profile_pic_nan_y', 'host_identity_verified_f_y', 'host_identity_verified_t_y', 'host_identity_verified_nan_y', 'instant_bookable_f_y', 'instant_bookable_t_y', 'property_type_Apartment', 'property_type_Bed & Breakfast', 'property_type_Boat', 'property_type_Boutique hotel', 'property_type_Bungalow', 'property_type_Cabin', 'property_type_Camper/RV', 'property_type_Castle', 'property_type_Cave', 'property_type_Chalet', 'property_type_Condominium', 'property_type_Dorm', 'property_type_Earth House', 'property_type_Guest suite', 'property_type_Guesthouse', 'property_type_Hostel', 'property_type_House', 'property_type_Hut', 'property_type_In-law', 'property_type_Island', 'property_type_Loft', 'property_type_Other', 'property_type_Serviced apartment', 'property_type_Tent', 'property_type_Timeshare', 'property_type_Tipi', 'property_type_Townhouse', 'property_type_Train', 'property_type_Treehouse', 'property_type_Vacation home', 'property_type_Villa', 'property_type_Yurt', 'cancellation_policy_flexible', 'cancellation_policy_moderate', 'cancellation_policy_strict', 'cancellation_policy_super_strict_30', 'cancellation_policy_super_strict_60', 'city_Boston', 'city_Chicago', 'city_DC', 'city_LA', 'city_NYC', 'city_SF', 'host_has_profile_pic_f', 'host_has_profile_pic_t', 'host_has_profile_pic_nan', 'host_identity_verified_f', 'host_identity_verified_t', 'host_identity_verified_nan', 'instant_bookable_f', 'instant_bookable_t']

In [45]:
print(encoded_Airbnb_df.columns)

Index(['log_price', 'accommodates', 'bathrooms', 'number_of_reviews',
       'review_scores_rating', 'bedrooms', 'beds', 'property_type_Apartment_x',
       'property_type_Bed & Breakfast_x', 'property_type_Boat_x',
       ...
       'city_NYC', 'city_SF', 'host_has_profile_pic_f',
       'host_has_profile_pic_t', 'host_has_profile_pic_nan',
       'host_identity_verified_f', 'host_identity_verified_t',
       'host_identity_verified_nan', 'instant_bookable_f',
       'instant_bookable_t'],
      dtype='object', length=160)